theme: jekyll-theme-minimal
title: "EMPIRE BREAKOUT"
description: "Empire Breakout Penetration Testing Walkthrough."
show_downloads: false
baseurl: "/Empire-BreakOut"
url: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

author:
  name: itstallam
  url: https://github.com/itstallam
